import { CoffeeEntry } from "./types";

/**
 * Initial coffee lots data
 */
export const SAMPLE_DATA: CoffeeEntry[] = [
  {
    producer: "Huila Reserve",
    farm: undefined,
    origin: "COLOMBIA",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Reserve Program - Premium selection",
    bags: 180,
    kgPerBag: 70,
    price: 1,
    currency: "USD",
    category: "regional",
    country: "USA",
  },
  {
    producer: "Ana Melva Sampertegui Sanchez - San Ignacio",
    farm: "San Ignacio",
    origin: "PERU",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Microlot from San Ignacio, Peru",
    bags: 18,
    kgPerBag: 35,
    price: 14.33,
    currency: "USD",
    category: "microlots",
    country: "USA",
  },
  {
    producer: "Elver Maluquis Guevara - Cutervo",
    farm: "Cutervo",
    origin: "PERU",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Microlot from Cutervo, Peru",
    bags: 16,
    kgPerBag: 35,
    price: 14.33,
    currency: "USD",
    category: "microlots",
    country: "USA",
  },
  {
    producer: "Clever Ander Flores Fernandez - San Ramon Huabal",
    farm: "San Ramon Huabal",
    origin: "PERU",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Microlot from San Ramon Huabal",
    bags: 16,
    kgPerBag: 35,
    price: 14.33,
    currency: "USD",
    category: "microlots",
    country: "USA",
  },
  {
    producer: "Rogert Ebert Acha - San Pablo",
    farm: "San Pablo",
    origin: "PERU",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Microlot from San Pablo, Peru",
    bags: 12,
    kgPerBag: 35,
    price: 12.13,
    currency: "USD",
    category: "microlots",
    country: "USA",
  },
  {
    producer: "Marta Isabel Cruzado Vasquez - El Diamante",
    farm: "El Diamante",
    origin: "PERU",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Microlot from El Diamante",
    bags: 9,
    kgPerBag: 35,
    price: 15.21,
    currency: "USD",
    category: "microlots",
    country: "USA",
  },
  {
    producer: "Marino Guevara Alejandria - San Antonio Huabal",
    farm: "San Antonio Huabal",
    origin: "PERU",
    varietal: "MIX",
    process: "NATURAL",
    score: "85",
    flavorProfile: "Natural process microlot",
    bags: 8,
    kgPerBag: 35,
    price: 15.55,
    currency: "USD",
    category: "microlots",
    country: "USA",
  },
  {
    producer: "Clever Angel Villanueva Rafael - Chontali",
    farm: "Chontali",
    origin: "PERU",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Microlot from Chontali",
    bags: 12,
    kgPerBag: 35,
    price: 12.13,
    currency: "USD",
    category: "microlots",
    country: "USA",
  },
  {
    producer: "Popayan Decaf",
    farm: undefined,
    origin: "COLOMBIA",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Decaffeinated Colombian coffee",
    bags: 102,
    kgPerBag: 70,
    price: 1,
    currency: "USD",
    category: "regional",
    country: "USA",
  },
  {
    producer: "Popayan Reserve",
    farm: undefined,
    origin: "COLOMBIA",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Reserved lot - High demand",
    bags: 200,
    kgPerBag: 70,
    price: 1,
    currency: "USD",
    category: "regional-plus",
    country: "USA",
  },
  {
    producer: "Popayan Decaf - Expected",
    farm: undefined,
    origin: "COLOMBIA",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Upcoming decaf shipment",
    bags: 58,
    kgPerBag: 70,
    price: 1,
    currency: "USD",
    category: "upcoming-coffee",
    country: "USA",
  },
  {
    producer: "Popayan Reserve - Expected",
    farm: undefined,
    origin: "COLOMBIA",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Incoming reserve lot",
    bags: 307,
    kgPerBag: 70,
    price: 1,
    currency: "USD",
    category: "upcoming-coffee",
    country: "USA",
  },
  {
    producer: "Popayan Decaf - Continental",
    farm: undefined,
    origin: "COLOMBIA",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Decaffeinated reserve option",
    bags: 58,
    kgPerBag: 70,
    price: 1,
    currency: "USD",
    category: "regional",
    country: "USA",
  },
  {
    producer: "Popayan Reserve - Continental",
    farm: undefined,
    origin: "COLOMBIA",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Premium reserve stock",
    bags: 303,
    kgPerBag: 70,
    price: 1,
    currency: "USD",
    category: "regional-plus",
    country: "USA",
  },
  {
    producer: "Sarava - Cerrado",
    farm: "Cerrado",
    origin: "BRAZIL",
    varietal: "MIX",
    process: "NATURAL",
    score: "85",
    flavorProfile: "Brazilian natural process specialty",
    bags: 100,
    kgPerBag: 59,
    price: 9.13,
    currency: "USD",
    category: "regional",
    country: "USA",
  },
  {
    producer: "Samba Reserve",
    farm: undefined,
    origin: "BRAZIL",
    varietal: "MIX",
    process: "NATURAL",
    score: "85",
    flavorProfile: "Brazilian reserve - premium lot",
    bags: 210,
    kgPerBag: 59,
    price: 8.93,
    currency: "USD",
    category: "regional-plus",
    country: "USA",
  },
  {
    producer: "Jairo Arcila - Santa Monica",
    farm: "Santa Monica",
    origin: "COLOMBIA",
    varietal: "CASTILLO",
    process: "WASHED",
    score: "85",
    flavorProfile: "Wine yeast fermentation - strawberry notes",
    bags: 25,
    kgPerBag: 24,
    price: 25.35,
    currency: "USD",
    category: "exotics",
    country: "USA",
  },
  {
    producer: "Felipe Arcila - Jardines del Encanto",
    farm: "Jardines del Encanto",
    origin: "COLOMBIA",
    varietal: "MARAGESHA",
    process: "NATURAL",
    score: "87",
    flavorProfile: "Exotic microlot - rare varietal",
    bags: 0,
    kgPerBag: 24,
    price: 3,
    currency: "USD",
    category: "exotics",
    country: "USA",
  },
  {
    producer: "Diofanor Ruíz - La Divisa",
    farm: "La Divisa",
    origin: "COLOMBIA",
    varietal: "JAVA",
    process: "NATURAL",
    score: "86",
    flavorProfile: "Natural fermentation - CM 96H process",
    bags: 5,
    kgPerBag: 24,
    price: 3,
    currency: "USD",
    category: "microlots",
    country: "USA",
  },
  {
    producer: "Jairo Arcila - La Castellana",
    farm: "La Castellana",
    origin: "COLOMBIA",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Regional plus selection",
    bags: 85,
    kgPerBag: 70,
    price: 3,
    currency: "USD",
    category: "regional-plus",
    country: "USA",
  },
  // UK Data
  {
    producer: "Huila Reserve UK",
    farm: undefined,
    origin: "COLOMBIA",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Reserve Program - Premium selection",
    bags: 150,
    kgPerBag: 70,
    price: 1,
    currency: "USD",
    category: "regional",
    country: "UK",
  },
  {
    producer: "Ana Melva Sampertegui Sanchez - San Ignacio UK",
    farm: "San Ignacio",
    origin: "PERU",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Microlot from San Ignacio, Peru",
    bags: 12,
    kgPerBag: 35,
    price: 14.33,
    currency: "USD",
    category: "microlots",
    country: "UK",
  },
  {
    producer: "Popayan Reserve UK",
    farm: undefined,
    origin: "COLOMBIA",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Reserved lot - High demand",
    bags: 180,
    kgPerBag: 70,
    price: 1,
    currency: "USD",
    category: "regional-plus",
    country: "UK",
  },
  {
    producer: "Sarava - Cerrado UK",
    farm: "Cerrado",
    origin: "BRAZIL",
    varietal: "MIX",
    process: "NATURAL",
    score: "85",
    flavorProfile: "Brazilian natural process specialty",
    bags: 95,
    kgPerBag: 59,
    price: 9.13,
    currency: "USD",
    category: "regional",
    country: "UK",
  },
  {
    producer: "Jairo Arcila - Santa Monica UK",
    farm: "Santa Monica",
    origin: "COLOMBIA",
    varietal: "CASTILLO",
    process: "WASHED",
    score: "85",
    flavorProfile: "Wine yeast fermentation - strawberry notes",
    bags: 20,
    kgPerBag: 24,
    price: 25.35,
    currency: "USD",
    category: "exotics",
    country: "UK",
  },
  // CANADA Data
  {
    producer: "Huila Reserve Canada",
    farm: undefined,
    origin: "COLOMBIA",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Reserve Program - Premium selection",
    bags: 160,
    kgPerBag: 70,
    price: 1,
    currency: "USD",
    category: "regional",
    country: "CANADA",
  },
  {
    producer: "Elver Maluquis Guevara - Cutervo Canada",
    farm: "Cutervo",
    origin: "PERU",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Microlot from Cutervo, Peru",
    bags: 14,
    kgPerBag: 35,
    price: 14.33,
    currency: "USD",
    category: "microlots",
    country: "CANADA",
  },
  {
    producer: "Popayan Decaf Canada",
    farm: undefined,
    origin: "COLOMBIA",
    varietal: "MIX",
    process: "WASHED",
    score: "85",
    flavorProfile: "Decaffeinated Colombian coffee",
    bags: 90,
    kgPerBag: 70,
    price: 1,
    currency: "USD",
    category: "regional",
    country: "CANADA",
  },
  {
    producer: "Samba Reserve Canada",
    farm: undefined,
    origin: "BRAZIL",
    varietal: "MIX",
    process: "NATURAL",
    score: "85",
    flavorProfile: "Brazilian reserve - premium lot",
    bags: 200,
    kgPerBag: 59,
    price: 8.93,
    currency: "USD",
    category: "regional-plus",
    country: "CANADA",
  },
  {
    producer: "Felipe Arcila - Jardines del Encanto Canada",
    farm: "Jardines del Encanto",
    origin: "COLOMBIA",
    varietal: "MARAGESHA",
    process: "NATURAL",
    score: "87",
    flavorProfile: "Exotic microlot - rare varietal",
    bags: 8,
    kgPerBag: 24,
    price: 3,
    currency: "USD",
    category: "exotics",
    country: "CANADA",
  },
];
